services:
  - type: web
    name: asistencia-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT Sistema_Asistencia:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: RESTAURANT_LAT
        value: 5.618553712703385
      - key: RESTAURANT_LON
        value: -73.81627418830061
      - key: GPS_RADIUS_METERS
        value: 50
      - key: QR_EXPIRATION_MINUTES
        value: 5
